config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index] do #Add param: :username, after :users to sub in username
  	resources :directions
  end
  get '/users/:id/confirm' => 'users#confirm'
  get '/users/:id/deny' => 'users#deny'

  get '/directions/all' => 'directions#all'
  get '/directions/:id/view' => 'directions#view'

  resources :sessions

  resources :password_resets

  root 'directions#all'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :d, only: [:show]

end

app/models/direction.rb
class Direction < ActiveRecord::Base

	belongs_to :user

	# Used only when a Direction is initially created
	def add_stats_on_creation
		self['published_at'] = Time.zone.now
		self['short_url'] = SecureRandom.urlsafe_base64

		if Direction.find_by_short_url(self.short_url) != nil
			self.errors.add(:url_error, 'Sorry, there was an error creating the unique URL for your directions. Please save your directions again.')
			return false
		else
			return true
		end
	end	

end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController

	skip_before_action :authorize, only: [:all, :view]
	skip_before_action :current_user, except: [:all, :view]
	before_action :confirm_user, except: [:all, :view]

	def all
		limit = 5
		@directions = Direction.order("published_at DESC").first(limit)
	end

	def view
		@direction = Direction.find(params[:id])
	end

	def index
		@directions = Direction.where(user_id: params[:user_id]).order("published_at DESC")
	end

	def show
		@direction = Direction.find(params[:id])
	end

	def new
		@direction = Direction.new
	end

	def create
		@direction = Direction.new(direction_params)

		if @direction.add_stats_on_creation
			if @direction.save
				render :show
			else
				flash.now[:danger] = @direction.errors.full_messages
				render :new
			end
		else
			flash.now[:danger] = @user.errors.get(:url_error)
			render :new
		end
	end

	def edit
		@direction = Direction.find(params[:id])
	end

	def update
	end

	def destroy
	end

private

	def direction_params
		params.require(:direction).permit(:title, :body, :user_id)
	end

end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/views/directions/all.html.erb
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
		<h1>Most recent directions:</h1>
	</div>
</div>

<% @directions.each do |direction| %>
	<div class="row">
		<div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
		  <h3><%= link_to direction.title, "/directions/#{direction[:id]}/view" %></h3>
		  <h5>Created by <%= direction.user.username %></h5>
		  <h5>Published <%= time_ago_in_words direction.published_at %> ago</h5>
		</div>
	</div>
<% end %>

app/views/directions/edit.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">

		<%= form_for @direction, url: user_directions_path do |d| %>

			<div class="form-group">
				<label for="title">Title:</label>
				<%= d.text_field :title, class: 'form-text-field form-control', placeholder: "Title" %>
			</div>

			<div class="form-group">
				<label for="body">Directions:</label>
				<%= d.text_area :body, class: 'form-control', rows: '10', cols: '60' %>
			</div>

			<%= d.submit 'Update Your Directions!', class: 'btn btn-primary' %>
			<%= link_to 'Cancel', user_directions_path, class: 'btn btn-default' %>

		<% end %>

	</div>
</div>

app/views/directions/index.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">

		<h1>My Directions</h1>
		<hr />
		<% @directions.each do |direction| %>
		  <h1><%= link_to direction.title, user_direction_path(@current_user.id, direction.id) %></h1>
		  
		  <p>
		    <%= markdown(direction.body) %>
		  </p>
		  <h5>Published <%= time_ago_in_words direction.published_at %> ago</h5>

		  <% if direction != @directions.last %>
		  <hr />
		  <% end %>
		<% end %>

	</div>
</div>

app/views/directions/new.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">

		<%= form_for @direction, url: user_directions_path do |d| %>

			<div class="form-group">
				<label for="title">Title:</label>
				<%= d.text_field :title, class: 'form-text-field form-control', placeholder: "Title" %>
			</div>

			<div class="form-group">
				<label for="body">Directions:</label>
				<%= d.text_area :body, class: 'form-control', rows: '10', cols: '60' %>
			</div>

			<p><%= d.submit 'Submit your .md post!', class: 'btn btn-default' %></p>

		<% end %>

	</div>
</div>

app/views/directions/show.html.erb
<h1><%= @direction.title %></h1>
<hr />
  
<p>
  <%= markdown(@direction.body) %>
</p>
<h4>Published <%= time_ago_in_words @direction.published_at %> ago</h4>

<p><%= link_to 'Edit these Directions', edit_user_direction_path %></p>

<p>Share These Directions: <%= d_url(@direction.short_url) %></p>

</p><%= link_to "Back to Index", user_directions_path %></p>

app/views/directions/view.html.erb
<h1><%= @direction.title %></h1>  
<p><%= markdown(@direction.body) %></p>
<h5>Published <%= time_ago_in_words @direction.published_at %> ago</h5>