config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index] do #Add param: :username, after :users to sub in username
  	resources :directions
  end
  get '/users/:id/confirm' => 'users#confirm'
  get '/users/:id/deny' => 'users#deny'

  get '/directions/all' => 'directions#all'
  get '/directions/:id/view' => 'directions#view'

  resources :sessions

  resources :password_resets

  root 'directions#all'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :d, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :directions, dependent: :destroy

	has_secure_password

	validates_presence_of :first_name, :last_name, :email, :password_confirmation, :username, :on => :create
	validates_presence_of :first_name, :last_name, :email, :password, :username, :on => :update_account
	validates_presence_of :email, :on => :send_password_reset

	before_create { generate_token(:auth_token) }

	# def to_param
	# 	username
	# end

	def check_existing
		self.errors.add(:bad_input, 'That email is already taken.') if User.find_by_email(self.email)
		self.errors.add(:bad_input, 'That username is already taken.') if User.find_by_username(self.username)
		
		if self.errors.get(:bad_input) != nil
			return false
		else
			return true
		end
	end

	def check_current
		user_email = User.find_by_email(self.email)
		user_name = User.find_by_username(self.username)

		self.errors.add(:bad_input, 'That email is already taken.') if user_email.id != self.id
		self.errors.add(:bad_input, 'That username is already taken.') if user_name.id != self.id
		
		if self.errors.get(:bad_input) != nil
			return false
		else
			return true
		end
	end

	def send_account_create
		generate_token(:account_create_token)
		self.account_create_sent_at = Time.zone.now
		save!
		UserMailer.account_create(self).deliver
	end

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end

	def update_account(update_user_params)
		update_user_params.each do |key, value|
			if self[key] != value
				self[key] = value
			end
			save!
		end
	end

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_action :authorize, only: [:new, :create, :confirm, :deny]
	skip_before_action :current_user, only: [:new, :create, :confirm, :deny]
	before_action :confirm_user, only: [:edit, :show, :update, :destroy]

	def new
		@user = User.new
	end

	def create
		user = User.new(user_params)

		if user.check_existing
			@user = user

			if @user.save
				@user.send_account_create
				flash[:success] = 'Please click on the link in your email to confirm your account.'
				redirect_to root_path
			else
				flash.now[:danger] = check_existing.errors.full_messages
				render :new
			end
		else
			flash[:danger] = user.errors.get(:bad_input)
			redirect_to new_user_path
		end
	end

	def confirm
		@user = User.find_by_account_create_token!(params[:id])

		if @user.account_create_confirmed_at != nil
			flash.now[:info] = 'You have already confirmed your account.'
		else
			@user.account_create_confirmed_at = Time.zone.now

			if @user.save
				cookies[:auth_token] = @user.auth_token
				params[:account_create_token] = @user.account_create_token
			else
				flash[:danger] = 'We\'re sorry, there was an error creating your account.'
			end
		end
	end

	def deny
		user = User.find_by_account_create_token!(params[:id])

		if user.account_create_confirmed_at == nil
			if user.destroy
				flash[:info] = 'The account associated with this email has been deleted. We apologize for the error.'
				redirect_to root_path
			else
				flash[:danger] = 'There was an error deleting the account associated with your email. Please contact support.'
			end
		else
			flash.now[:info] = 'The account associated with this email has already been confirmed. It can only be deleted by the authorized user.'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if update_user_params[:current_password].length == 0
			flash.now[:danger] = 'Please enter your password to update your information.'
			render :edit
		elsif @user.authenticate(update_user_params[:current_password]) != @user
			flash.now[:danger] = 'The password you entered does not match the current account password.'
			render :edit
		elsif @user.authenticate(update_user_params[:current_password]) == @user
			@user.assign_attributes(update_user_params.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation))

			if @user.check_current
				if @user.save
					render :show
				else
					flash.now[:danger] = @user.errors.full_messages
					render :edit
				end
			else
				flash.now[:danger] = @user.errors.get(:bad_input)
				render :edit
			end
		end
	end

	def destroy
		@user = User.find(params[:id])

		if delete_user_params[:current_password].length == 0
			flash.now[:danger] = 'Please enter your password to delete your account.'
			render :show
		elsif @user.authenticate(delete_user_params[:current_password]) != @user
			flash.now[:danger] = 'The password you entered does not match the current account password.'
			render :show
		elsif @user.authenticate(delete_user_params[:current_password]) == @user
			if User.destroy_all(id: params[:id])
				flash[:success] = 'You have successfully deleted your account.'
				session[:id] = nil
				cookies.delete(:auth_token)
				redirect_to root_path
			else
				flash[:danger] = 'Your account was not deleted.'
				render :edit
			end
		end
	end

private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
	end

	def update_user_params
		params.require(:user).permit(:first_name, :last_name, :email, :username, :current_password, :password, :password_confirmation)
	end

	def delete_user_params
		params.require(:user).permit(:current_password)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">

		<% if flash[:info] == nil and params[:account_create_token] != nil %>
			<p>Thank you for creating your account!</p>
		<% end %>
		
		<p>You may begin creating directions <%= link_to 'here', new_user_direction_path(@user.id) %>.</p>

	</div>
</div>

app/views/users/create.html.erb
<%= params %>
<br>
<%= params[:user][:email] %>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">



		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">Edit My Information</h3>
		  </div>
		  <%= form_for @user do |f| %>
		  <div class="panel-body">

					<div class="form-group">
						<label for="first_name">First Name:</label>
						<%= f.text_field :first_name, class: 'form-text-field form-control', placeholder: 'First Name' %>
					</div>

					<div class="form-group">
						<label for="last_name">Last Name:</label>
						<%= f.text_field :last_name, class: 'form-text-field form-control', placeholder: 'Last Name' %>
					</div>

					<div class="form-group">
						<label for="username">Username:</label>
						<%= f.text_field :username, class: 'form-text-field form-control', placeholder: 'Username' %>
					</div>
					 
					<div class="form-group">
						<label for="email">Email:</label>
						<%= f.text_field :email, class: 'form-text-field form-control', placeholder: 'Email' %>
					</div>
				
					<div class="form-group">
						<label for="password">Password:</label>
						<%= f.password_field :current_password, class: 'form-text-field form-control', placeholder: 'Password' %>
					</div>

		  </div>
		  <div class="panel-footer"><%= f.submit 'Update My Account', class: 'btn btn-primary' %></div>
		  <% end %><!-- End of user info form -->

		</div><!-- End of user info panel -->

	</div>
</div>

<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
		
		<div class="panel panel-primary">

		  <div class="panel-heading">
		    <h3 class="panel-title">Change My Password</h3>
		  </div>

		  <%= form_for @user, :namespace => 'pw' do |f| %>
		  <div class="panel-body">

				<div class="form-group">
					<label for="password">Current Password:</label>
					<%= f.password_field :current_password, class: 'form-text-field form-control', placeholder: 'Current Password' %>
				</div>

				<div class="form-group">
					<label for="password">New Password:</label>
					<%= f.password_field :password, class: 'form-text-field form-control', placeholder: 'New Password' %>
				</div>
				
				<div class="form-group">
					<label for="password_confirmation">Confirm New Password:</label>
					<%= f.password_field :password_confirmation, class: 'form-text-field form-control', placeholder: 'Confirm New Password' %>
				</div>

		  </div>
		  <div class="panel-footer"><%= f.submit 'Update My Password', class: 'btn btn-primary' %></div>
		  <% end %><!-- End of password form -->

		</div><!-- End of password panel -->

	</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">

		<div class="loginForm">
		<%= form_for @user, url: users_path do |f| %>

			<div class="form-group">
				<label for="first_name">First Name:</label>
				<%= f.text_field :first_name, class: 'form-text-field form-control', placeholder: 'First Name' %>
			</div>

			<div class="form-group">
				<label for="last_name">Last Name:</label>
				<%= f.text_field :last_name, class: 'form-text-field form-control', placeholder: 'Last Name' %>
			</div>

			<div class="form-group">
				<label for="username">Username:</label>
				<%= f.text_field :username, class: 'form-text-field form-control', placeholder: 'Username' %>
			</div>
				 
			<div class="form-group">
				<label for="email">Email:</label>
				<%= f.text_field :email, class: 'form-text-field form-control', placeholder: 'Email' %>
			</div>
			
			<div class="form-group">
				<label for="password">Password:</label>
				<%= f.password_field :password, class: 'form-text-field form-control', placeholder: 'Password' %>
			</div>
			
			<div class="form-group">
				<label for="password_confirmation">Confirm Password:</label>
				<%= f.password_field :password_confirmation, class: 'form-text-field form-control', placeholder: 'Confirm Password' %>
			</div>
			
			<p><%= f.submit 'Create your account', class: 'btn btn-default' %></p>

		<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">

		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">My Account Information</h3>
		  </div>
		  <div class="panel-body">
		  	<p>First name: <%= @user.first_name %></p>
				<p>Last name: <%= @user.last_name %></p>
				<p>Username: <%= @user.username %></p>
				<p>Email: <%= @user.email %></p>
		  </div>
		  <div class="panel-footer"><%= link_to 'Edit My Account', edit_user_path(@current_user), role: 'button', class: 'btn btn-primary' %></div>
		</div>

		<div class="panel panel-danger">
		  <div class="panel-heading">
		    <h3 class="panel-title">Delete My Account</h3>
		  </div>
		  <div class="panel-body">
		  	Please click on the button below if you wish to delete your account. You will be asked to confirm your decision.
		  </div>
		  <div class="panel-footer"><button type="button" class="btn btn-danger" data-toggle="modal" data-target=".delete-acct-modal">Delete My Account</button></div>
		</div>
		
		<div class="modal fade delete-acct-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
		  <div class="modal-dialog modal-sm">
		    <div class="modal-content">
		    <%= form_for(@user, :html => { :method => :delete }) do |f| %>
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel">Delete Your Account?</h4>
		      </div>
		      <div class="modal-body">
		        <p>Please note: if you delete your account, all of your personal information and all of the directions that you've written will be deleted as well. This action cannot be undone!</p>

		        <p>If you are certain you want to do this, please enter your password below and click on "Yes, delete my account."</p>

		        <div class="form-group">
							<label for="password">Password:</label>
							<%= f.password_field :current_password, class: 'form-text-field form-control', placeholder: 'Password' %>
						</div>
		      </div>
		      <div class="modal-footer">
	        	<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	        	<%= f.submit 'Yes, delete my account', method: 'delete', class: 'btn btn-danger' %>
	      	</div>
	      <% end %>
		    </div>
		  </div>
		</div>

	</div>
</div>

app/views/users/update.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">

	<%= params %>

	</div>
</div>

<div class="row">
  <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">

	<% if flash[:info] == nil %>
		<p>Thank you for creating your account!</p>
	<% end %>

	<p>You may begin creating directions <%= link_to 'here', edit_session_path, target: '_blank' %>.</p>

	</div>
</div>