config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index] do #Add param: :username, after :users to sub in username
  	resources :directions
  end
  get '/users/:id/confirm' => 'users#confirm'
  get '/users/:id/deny' => 'users#deny'

  get '/directions/all' => 'directions#all'
  get '/directions/:id/view' => 'directions#view'

  resources :sessions

  resources :password_resets

  root 'directions#all'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  resources :d, only: [:show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>DirectionR</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">DirectionR</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	      	<% if @current_user %>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><%= link_to "View My Directions", user_directions_path(@current_user) %></li>
		            <li><%= link_to "View My Account", user_path(@current_user.id) %></li>
		            <li role="separator" class="divider"></li>
		            <li><%= link_to "Log Out", logout_path %></li>
		          </ul>
		        </li>
		        <li id="newDirectionButton"><%= link_to(raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Directions'), new_user_direction_path(@current_user.id), {:class => 'navbar-right'}) %></li>
		      <% else %>
		      	<li id="createAccount"><%= link_to "Create Account", new_user_path %></li>
		      	<li id="login"><%= link_to "Log In", login_path %></li>
		      <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="row">
		<div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">

		<% flash.each do |key, value| %>
		  <div class='alert alert-<%= key %>' role='alert'>
		    <% if value.class != Array %>
		    	<%= value %>
		    <% else %>
			    <% value.each do |msg| %>
			      <p><%= msg %></p>
			    <% end %>
				<% end %>
		  </div>
		<% end %>

		</div>
	</div>

<%= yield %>

</body>
</html>